# Generated by Django 4.0.4 on 2022-06-09 14:00

import abstracts.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='время обновления')),
                ('datetime_deleted', models.DateTimeField(blank=True, null=True, verbose_name='время удаления')),
                ('studio', models.CharField(default='', max_length=100, verbose_name='студия')),
                ('rating', models.IntegerField(verbose_name='рейтинг')),
            ],
            options={
                'verbose_name': 'аниме',
                'verbose_name_plural': 'аниме',
                'ordering': ('-datetime_created',),
            },
            bases=(models.Model, abstracts.validators.AbstractValidator),
        ),
        migrations.CreateModel(
            name='ReleaseDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.CharField(max_length=20, verbose_name='выпущен')),
                ('date', models.DateTimeField(verbose_name='дата')),
            ],
            options={
                'verbose_name': 'дата выпуска ',
                'verbose_name_plural': 'даты выпуска ',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='имя')),
                ('link', models.TextField(verbose_name='ссылка')),
            ],
            options={
                'verbose_name': 'дата выпуска',
                'verbose_name_plural': 'даты выпуска',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='имя')),
                ('cabinet', models.ManyToManyField(related_name='genres', to='cabinet.cabinet', verbose_name='аниме')),
            ],
            options={
                'verbose_name': 'жанр',
                'verbose_name_plural': 'жанры',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_en', models.TextField(default='', verbose_name='текст на английском')),
                ('text_ru', models.TextField(default='', verbose_name='текст на русском')),
                ('cabinet', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cabinet.cabinet', verbose_name='аниме')),
            ],
            options={
                'verbose_name': 'описание',
                'verbose_name_plural': 'описания',
                'ordering': ('-id',),
            },
        ),
        migrations.AddField(
            model_name='cabinet',
            name='release_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cabinet.releasedate', verbose_name='дата выпуска'),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='title',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cabinet.title', verbose_name='название'),
        ),
    ]
